# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerServiceconnection: 'callmeDharam'
  imagerepository: 'callmedharam/staticweb'

stages:
- stage: 
  displayName: Login into DockerHub
  jobs:
  - job: Login
    displayName: Login Into Docker Hub
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/static-website/Dockerfile'
        tags: |
          $(tag)
