# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
resources:
- repo: self



variables:
  tag: '$(Build.BuildId)'
  dockerImageTag: 'latest' 
  dockerServiceconnection: 'Callmedharam@DockerHub'  # Ensure this is correct 
  imagerepository: 'callmedharam/staticweb'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
pool:
    vmImage: 'ubuntu-latest'
stages:
- stage: Login
  displayName: Login into DockerHub
  jobs:
  - job: Login
    displayName: Login Into Docker Hub
      # Add this to specify an agent
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerServiceconnection)'
        command: login

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        Dockerfile: '$(dockerfile)'
        containerRegistry: '$(dockerServiceconnection)'
        repository: '$(imagerepository)'
        tags: |
          $(tag)
        #  $(dockerImageTag)
         
- stage: Push

  displayName: Pushing Image 
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: $(dockerServiceconnection)
        
      #  Dockerfile: $(imagerepository)
        command:  push
        repository: $(imagerepository)
        tags: |
          $(tag)
          $(dockerImageTag)       
    
